package com.yuan.mybatis.dao;

import java.util.List;

import org.apache.ibatis.annotations.ResultType;
import org.apache.ibatis.annotations.Select;

import com.mybatis.www.model.Fruits;

public interface FruitsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fruits
	 * @mbggenerated  Tue Nov 14 14:55:49 CST 2017
	 */
	int deleteByPrimaryKey(String fId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fruits
	 * @mbggenerated  Tue Nov 14 14:55:49 CST 2017
	 */
	int insert(Fruits record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fruits
	 * @mbggenerated  Tue Nov 14 14:55:49 CST 2017
	 */
	int insertSelective(Fruits record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fruits
	 * @mbggenerated  Tue Nov 14 14:55:49 CST 2017
	 */
	Fruits selectByPrimaryKey(String fId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fruits
	 * @mbggenerated  Tue Nov 14 14:55:49 CST 2017
	 */
	int updateByPrimaryKeySelective(Fruits record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fruits
	 * @mbggenerated  Tue Nov 14 14:55:49 CST 2017
	 */
	int updateByPrimaryKey(Fruits record);
	@Select(value="select * from fruits")
	@ResultType(value=com.mybatis.www.model.Fruits.class)
	 List<Fruits> getAllFruits();
}