package com.yuan.mybatis.dao;

import com.mybatis.www.model.Student;

public interface StudentMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table student
	 * @mbggenerated  Tue Nov 14 18:12:19 CST 2017
	 */
	int insert(Student record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table student
	 * @mbggenerated  Tue Nov 14 18:12:19 CST 2017
	 */
	int insertSelective(Student record);
}