package com.mybatis.www.model;

import java.io.Serializable;
import java.math.BigDecimal;

public class Fruits implements Serializable{

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fruits.f_id
	 * @mbggenerated  Tue Nov 14 14:55:49 CST 2017
	 */
	private String f_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fruits.s_id
	 * @mbggenerated  Tue Nov 14 14:55:49 CST 2017
	 */
	private Integer s_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fruits.f_name
	 * @mbggenerated  Tue Nov 14 14:55:49 CST 2017
	 */
	private String f_name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fruits.f_price
	 * @mbggenerated  Tue Nov 14 14:55:49 CST 2017
	 */
	private BigDecimal fPrice;
	public String getF_id() {
		return f_id;
	}
	public void setF_id(String f_id) {
		this.f_id = f_id;
	}
	public Integer getS_id() {
		return s_id;
	}
	public void setS_id(Integer s_id) {
		this.s_id = s_id;
	}
	public String getF_name() {
		return f_name;
	}
	public void setF_name(String f_name) {
		this.f_name = f_name;
	}
	public BigDecimal getfPrice() {
		return fPrice;
	}
	public void setfPrice(BigDecimal fPrice) {
		this.fPrice = fPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fruits.f_id
	 * @return  the value of fruits.f_id
	 * @mbggenerated  Tue Nov 14 14:55:49 CST 2017
	 */
	
}