package com.mybatis.www.model;

import java.io.Serializable;
import java.util.Date;

public class Student implements Serializable{

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column student.S
	 * @mbggenerated  Tue Nov 14 18:12:19 CST 2017
	 */
	private String s;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column student.Sname
	 * @mbggenerated  Tue Nov 14 18:12:19 CST 2017
	 */
	private String sname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column student.Sage
	 * @mbggenerated  Tue Nov 14 18:12:19 CST 2017
	 */
	private Date sage;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column student.Ssex
	 * @mbggenerated  Tue Nov 14 18:12:19 CST 2017
	 */
	private String ssex;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column student.S
	 * @return  the value of student.S
	 * @mbggenerated  Tue Nov 14 18:12:19 CST 2017
	 */
	public String getS() {
		return s;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column student.S
	 * @param s  the value for student.S
	 * @mbggenerated  Tue Nov 14 18:12:19 CST 2017
	 */
	public void setS(String s) {
		this.s = s;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column student.Sname
	 * @return  the value of student.Sname
	 * @mbggenerated  Tue Nov 14 18:12:19 CST 2017
	 */
	public String getSname() {
		return sname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column student.Sname
	 * @param sname  the value for student.Sname
	 * @mbggenerated  Tue Nov 14 18:12:19 CST 2017
	 */
	public void setSname(String sname) {
		this.sname = sname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column student.Sage
	 * @return  the value of student.Sage
	 * @mbggenerated  Tue Nov 14 18:12:19 CST 2017
	 */
	public Date getSage() {
		return sage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column student.Sage
	 * @param sage  the value for student.Sage
	 * @mbggenerated  Tue Nov 14 18:12:19 CST 2017
	 */
	public void setSage(Date sage) {
		this.sage = sage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column student.Ssex
	 * @return  the value of student.Ssex
	 * @mbggenerated  Tue Nov 14 18:12:19 CST 2017
	 */
	public String getSsex() {
		return ssex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column student.Ssex
	 * @param ssex  the value for student.Ssex
	 * @mbggenerated  Tue Nov 14 18:12:19 CST 2017
	 */
	public void setSsex(String ssex) {
		this.ssex = ssex;
	}
}